site_name: Audition Toolkit🎼🎹 User guide
site_url: https://quantalept.github.io/at-docs/

nav:
  - Home(AT)🙏 : index.md
  - Advanced edit 🎵📊🎚️: equalizer.md
  - Record 🎤🎧 : record.md
  - Trim  ✂️ : trim.md
  - Voice Changer 🗣️🎙️ : voice_changer.md
  - Split ✂️✂️ : split.md
  - Karaoke Extractor 🗣️🚫🎶 : karaoke.md
  - Reverse 🔄 : reverse.md
  - Magic Enhancer 🎙️🎚️🔊: enhancer.md
  - Pro Features 🚀 : pro.md
  - Customization 🎨 : quick_start.md
  - General Functions 🎉 : preview.md



theme:
    name: material
    palette:
      scheme: default
      primary: custom  # required to allow custom color override

extra_css:
  - extra.css
